/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#003919",
        "secondary-fixed": "#f0dbff",
        "on-secondary-fixed": "#2c0051",
        "secondary-container": "#6f00be",
        "secondary-fixed-dim": "#ddb7ff",
        "outline": "#869486",
        "primary-container": "#4ade80",
        "surface-variant": "#2f372f",
        "outline-variant": "#3d4a3e",
        "background": "#0e150f",
        "primary": "#6bfb9a",
        "on-primary-container": "#005e2d",
        "on-tertiary-fixed-variant": "#6c3a0f",
        "surface-container-highest": "#2f372f",
        "error": "#ffb4ab",
        "surface-container-lowest": "#09100a",
        "on-primary-fixed": "#00210c",
        "surface-container-low": "#161d17",
        "primary-fixed-dim": "#4de082",
        "on-tertiary-container": "#794418",
        "surface-container": "#1a211b",
        "on-secondary-fixed-variant": "#6900b3",
        "inverse-on-surface": "#2b322b",
        "surface-container-high": "#242c25",
        "surface-tint": "#4de082",
        "on-tertiary": "#4f2500",
        "error-container": "#93000a",
        "on-surface": "#dde5da",
        "on-secondary-container": "#d6a9ff",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb784",
        "primary-fixed": "#6dfe9c",
        "surface": "#0e150f",
        "tertiary-container": "#ffb47f",
        "on-background": "#dde5da",
        "on-tertiary-fixed": "#301400",
        "inverse-primary": "#006d36",
        "inverse-surface": "#dde5da",
        "on-surface-variant": "#bccabb",
        "on-primary-fixed-variant": "#005227",
        "tertiary-fixed": "#ffdcc6",
        "on-error": "#690005",
        "tertiary": "#ffd9c1",
        "on-secondary": "#490080",
        "surface-bright": "#333b34",
        "secondary": "#ddb7ff",
        "surface-dim": "#0e150f",
        // Additional utility colors
        "pure-black": "#000000",
        "panel-dark": "#121212",
        "panel-darker": "#080808",
        "border-subtle": "#1F2937",
        "neon-green": "#4ADE80",
        "neon-purple": "#A855F7",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "base": "4px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "gutter": "16px",
        "container-max": "1440px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "code-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "450" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      },
      boxShadow: {
        "neon-glow": "0 0 8px 0 rgba(74, 222, 128, 0.3)",
        "neon-glow-primary": "0 0 8px 0 rgba(74, 222, 128, 0.3)",
        "neon-glow-secondary": "0 0 8px 0 rgba(168, 85, 247, 0.3)",
        "neon-glow-lg": "0 0 16px 2px rgba(74, 222, 128, 0.4)",
        "neon-glow-purple-lg": "0 0 16px 2px rgba(168, 85, 247, 0.4)",
      }
    },
  },
  plugins: [],
}
